[build]
  command = "echo Building functions"
  functions = "functions"
  include = [
    "views/**"
  ]
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
